// auto-generated by Fins.AdminTools.ModelBuilder.

inherit Fins.Model.DirectAccessInstance;
string context_name = "_default";
string type_name = "Font";

string get_descriptor()
{
  if(master_object && master_object->describe)
    return (string)this["Series"] + " " + this["size"];
  else return ("huh? " + get_id());
}



