// auto-generated by Fins.AdminTools.ModelBuilder.

inherit Fins.Model.DirectAccessInstance;
string context_name = "_default";
string type_name = "Series";


string get_descriptor()
{
  if(master_object && master_object->describe)
    return this["series"] + " " + this["name"];
  else return ("huh? " + get_id());
}

