// auto-generated by Fins.AdminTools.ModelBuilder for table fonts.

inherit Fins.Model.DataObject;

array(string) field_order = ({
    "id",
    "Series",
    "size",
    "matcase_type",
    "location",
    "condition",
    "Matrices",
    "comments"
});

void post_define(Fins.Model.DataModelContext context)
{
// Add any post configuration logic here
// set_alternate_key("myalternatekey");

}

