// auto-generated by Fins.AdminTools.ModelBuilder for table series.

inherit Fins.Model.DataObject;

void post_define(Fins.Model.DataModelContext context)
{
// Add any post configuration logic here

set_alternate_key("series");

}

