<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <title>CompCAT: Log In</title>

<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />

<link rel="stylesheet" type="text/css" media="screen" href="/static/Underground.css" />
<style type="text/css">
        @import url("/dojo/dojo/resources/dojo.css")
        @import url("/dojo/dijit/themes/tundra/tundra.css");
        @import url("/dojo/dojox/layout/resources/FloatingPane.css");
        @import url("/dojo/dojox/layout/resources/ResizeHandle.css");
        @import url("/dojo/dojo/resources/dnd.css");
</style>

</head>

<body class="tundra">
<!-- wrap starts here -->
<div id="wrap">

		<!-- header -->
		<div id="header">			
					
			<span id="slogan">monotype computer interface tools</span>
			
			<!-- tabs -->
			<ul>
			</ul>
											
		</div>
		
		<div id="header-logo">			
			
			<div id="logo">comp<span class="red">cat</span></div>		
			
						
		</div>
		
       	<div id="main">


<div><font color="red"><i><%flash%></i></font></div>

<%yield%>

	</div> <!-- main -->

<!-- wrap ends here -->
</div>
		
<!-- footer starts here -->
<div class="footer">
	
		<p>	
		    &copy; 2005-2016 H William Welliver III

            &nbsp;&nbsp;&nbsp;&nbsp;

	    	<a href="http://bill.welliver.org/space/letterpress/monotype">compcat</a>

		    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		    <%action_link controller="/"%>Home</a>
		</p>
		
</div>	
	
</body>
</html>

