// auto-generated by Fins.AdminTools.ModelBuilder for table font_schemes.
inherit Fins.Model.DataObject;

string table_name = "font_schemes";
string instance_name = "Font_scheme";

void post_define(Fins.Model.DataModelContext context)
{
  // Add any post configuration logic here
  // set_alternate_key("myalternatekey");
  belongs_to(context, "User", "owner", "owner_id");
  set_autosave(0);
}
