// auto-generated by Fins.AdminTools.ModelBuilder for table matcasearrangements.

inherit Fins.Model.DataObject;

string table_name = "matcasearrangements";

void post_define(object context)
{
// Add any post configuration logic here

  set_alternate_key("name");
  belongs_to(context, "User", "owner", "owner_id");
}

