// auto-generated by Fins.AdminTools.ModelBuilder for table preferences.

inherit Fins.Model.DataObject;

string table_name="preferences";

void post_define()
{
// Add any post configuration logic here

// set_alternate_key("myalternatekey");
  fields->value->len=256;

}

