// auto-generated by Fins.AdminTools.ModelBuilder for table ribbon_configs.
inherit Fins.Model.DataObject;

string table_name = "ribbon_configs";
string instance_name = "Ribbon_config";

void post_define(Fins.Model.DataModelContext context)
{
  // Add any post configuration logic here
  // set_alternate_key("myalternatekey");
}
