// auto-generated by Fins.AdminTools.ModelBuilder for table stopbars.

string table_name="stopbars";

inherit Fins.Model.DataObject;

void post_define(object context)
{
// Add any post configuration logic here

  set_alternate_key("name");
  belongs_to(context, "User", "owner", "owner_id");
}

