// auto-generated by Fins.AdminTools.ModelBuilder for table stopbars.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here

  set_alternate_key("name");
  belongs_to(context, "User", "owner", "owner_id");
}

